### ISSUE TITLE
SharedClasses.SCM01.* failure due to String mismatch

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9-systemtest#37]
Tests need to update to match `soft full` for JDK10

```
SCC stderr 
SCC stderr Cache is 63% soft full
SCC stderr 
SCC stderr Cache is accessible to current user = true
STF 04:06:10.345 - Monitoring Report Summary:
STF 04:06:10.345 -   o Process SCC ended with the expected exit code (1)
**FAILED** at step 7 (Print Shared Classes Cache Stats). Expected return value=0 Actual=0 at /home/jenkins/workspace/openjdk10_j9_systemtest_ppc64le_linux/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15311944025646/SharedClasses.SCM01.SingleCL_0/20180710-040416-SharedClasses/execute.pl line 173.
STF 04:06:10.436 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_j9_systemtest_ppc64le_linux/54/tapResults/

**Comment by llxia** [comment]
fyi @Mesbah-Alam

**Comment by llxia** [comment]
This is the same issue as https://github.com/eclipse/openj9-systemtest/issues/33
Instead of fixing test one by one, could we make a common function for same check?

**Comment by Mesbah-Alam** [comment]
@llxia : The test's criteria had been updated since this defect was seen, and the test has been passing since: https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK11-linux_ppc-64_cmprssptrs_le/148/tapResults/

We should close this defect at this point. Any new failure may be tracked by new issues.
